### ISSUE TITLE
segfault when using --learn option with javac

### ISSUE THREAD

**Issue by nanthiel** [thestinger/playpen#44]
This is my test case:

    sudo playpen\
        -l syscalls_java.txt\
        --mount-proc\
        --bind /bin\
        --bind /lib\
        --bind /lib64\
        --bind /usr\
        --bind extra\
        -u matej\
        sandbox\
         -- sh -c 'cp /extra/Test.java . && javac Test.java && java Test'

`extra` is the dir that includes the `Test.java` file, which contains:

    public class Test {
        public static void main(String[] args) {
            System.out.println("I'm secure!");
        }
    }

Running this prints:

    sh: line 1:     2 Segmentation fault      (core dumped) javac Test.java
    playpen: application terminated with error code 139

But this works fine:

    sudo playpen\
        -S syscalls_all.txt\
        --mount-proc\
        --bind /bin\
        --bind /lib\
        --bind /lib64\
        --bind /usr\
        --bind extra\
        -u matej\
        sandbox\
        -- sh -c 'cp /extra/Test.java . && javac Test.java && java Test'

`syscalls_all.txt` contains the list of all 314 system calls.

The `sandbox` directory consists of exactly:

    sandbox
    ├── bin
    ├── dev
    │   └── shm
    ├── etc
    │   ├── java-7-openjdk
    │   │   └── amd64
    │   │       └── jvm.cfg
    │   ├── nsswitch.conf
    │   └── passwd
    ├── extra
    ├── home
    │   └── matej
    ├── lib
    ├── lib64
    ├── proc
    ├── run
    ├── sbin
    ├── srv
    ├── sys
    ├── tmp
    ├── usr
    └── var
        └── tmp

I'm using the newest master branch of playpen.

`strace` itself works on the process (even inside playpen), if I wanted to awk my way through the needed system calls.

**Comment by thestinger** [comment]
Closing in favour of #48. I'm nearly certain that it's the issue here.

**Comment by thestinger** [comment]
This should be fixed by 0d7727046ec63b2d6963fb07899f63845fbbfecd.
