### ISSUE TITLE
Error on fedora 21

### ISSUE THREAD

**Issue by ekarlso** [thestinger/playpen#46]
munmap(0x7f48121da000, 4096)            = 0
epoll_create1(EPOLL_CLOEXEC)            = 3
rt_sigprocmask(SIG_BLOCK, [HUP INT TERM CHLD], NULL, 8) = 0
signalfd4(-1, [HUP INT TERM CHLD], 8, O_CLOEXEC) = 4
epoll_ctl(3, EPOLL_CTL_ADD, 4, {EPOLLIN, {u32=4, u64=4}}) = 0
pipe([5, 6])                            = 0
pipe([7, 8])                            = 0
fcntl(7, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(7, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
pipe([9, 10])                           = 0
fcntl(9, F_GETFL)                       = 0 (flags O_RDONLY)
fcntl(9, F_SETFL, O_RDONLY|O_NONBLOCK)  = 0
epoll_ctl(3, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=0, u64=0}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=7}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 9, {EPOLLIN, {u32=9, u64=9}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLOUT|EPOLLET, {u32=6, u64=6}}) = 0
clone(child_stack=0, flags=CLONE_NEWNS|CLONE_NEWUTS|CLONE_NEWIPC|CLONE_NEWPID|CLONE_NEWNET|SIGCHLD) = -1 EPERM (Operation not permitted)
write(2, "playpen: ", 9playpen: )                = 9
write(2, "clone", 5clone)                    = 5
write(2, ": ", 2: )                       = 2
write(2, "Operation not permitted\n", 24Operation not permitted
) = 24
exit_group(1)                           = ?
+++ exited with 1 +++
[fedora@play ~]$ strace ./bin/playpen $HOME/versions/v0.10.2 --mount-proc --devices=/dev/urandom:r,/dev/null:w --memory-limit=256 -l whitelist --user=root -- /bin/echo

Any idea on that ?

**Comment by thestinger** [comment]
It needs to be run as root right now. It's likely that it could be ported to use unprivileged user namespaces instead of having this requirement.
