### ISSUE TITLE
handle signals properly with ptrace in the learning mode

### ISSUE THREAD

**Issue by thestinger** [thestinger/playpen#48]
It should detect whether a signal is the cause of the SIGTRAP and raise it for the traced process.

**Comment by Limvot** [comment]
Just commenting that I have a similar problem to the reporter in #44 when trying to have it learn a gcc call.

**Comment by thestinger** [comment]
@Limvot: Hm, that might be a different issue - GCC has worked for me in the past. Is it a 32-bit GCC on a 64-bit OS by any chance? The current system call whitelisting doesn't allow multiarch.

**Comment by thestinger** [comment]
(it could be added via a flag, but so far I haven't had a need for it)

**Comment by Limvot** [comment]
Thanks for responding! Just checked, both are 64 bit. Like the other reporter, it works fine if all syscalls are allowed. I can weed them out from there, so it's not a huge deal. Thanks!
