### ISSUE TITLE
Continous output evades timeout

### ISSUE THREAD

**Issue by jhass** [thestinger/playpen#50]
bug.c
```c
#include <stdio.h>
int main(void) {
  while (1) printf("a");
}
```
whitelist
```
brk
mmap2
access
open
fstat64
close
read
set_thread_area
mprotect
munmap
write
```
```sh
# playpen sandbox -u nobody -S whitelist -t 1 -- /bug
```

Expected: Timeout triggered. Actual: No timeout triggered. Verified on git master and version 10.

> Linux 3.14.40-2-lts \#1 SMP Fri May 1 14:20:55 CEST 2015 i686 GNU/Linux

**Comment by thestinger** [comment]
Your example stops reliable for me, but I could understand why it might not. The event loop drains the input pipe from the child into `stdout` until it hits again so it might be possible for it to go forever if the pipe is filling faster than it's being drained.

Does it still happen if you redirect the Playpen output to `/dev/null`? That would be a strong indication that this is the problem. It wouldn't be hard for me to fix it.

**Comment by jhass** [comment]
No, redirecting output to `/dev/null` makes the timeout trigger properly. But you're right, it's probably the underpowered VPS instead of it being 32bit.

Other symptoms, with stdout not redirected, are that `Ctrl+C` is no longer sent, at least the handler doesn't seem to fire anymore. SIGQUIT (`Ctrl+Alt+\`) eventually fires after a few attempts, I suppose because there is no trap on it.

**Comment by thestinger** [comment]
This might fix the problem:

```diff
diff --git a/playpen.c b/playpen.c
index cd22231..ba35e0a 100644
--- a/playpen.c
+++ b/playpen.c
@@ -196,12 +196,14 @@ static void epoll_add(int epoll_fd, int fd, uint32_t events) {
 // This could often use `splice`, but it will not always work with `stdout` and `stderr`.
 static void copy_pipe_to(int in_fd, int out_fd) {
     ssize_t n;
+    unsigned iterations = 0;
     do {
         uint8_t buffer[BUFSIZ];
         n = read(in_fd, buffer, sizeof buffer);
         if (check_eagain(n, "read")) return;
         check_posix(write(out_fd, buffer, (size_t)n), "write");
-    } while (n != 0);
+        iterations++;
+    } while (n != 0 && iterations < 100);
 }
 
 static int get_syscall_nr(const char *name) {
```

**Comment by thestinger** [comment]
It could also just not loop at all, which would make the timeout as precise as possible.

**Comment by jhass** [comment]
It certainly improved it a lot, the timeout seems to always trigger now. Remaining minor issues seem to be that `Ctrl+C` now only fires when the timeout would hit and I'm seeing about 1.3 seconds extra runtime here, both with which I could live from my side.

**Comment by thestinger** [comment]
Can you try with that `iterations < 100` part changed to `iterations < 1`? I think writing to the TTY is probably just *really* slow.

**Comment by jhass** [comment]
Small correction: Ctrl+C triggers after the 1.3 seconds apparently, I just wasn't fast enough. Another possible factor might be that I run this over SSH, though I've also seen this when reading playpens stdout over a pipe when spawned from another process.

`iterations < 1` reduced the extra delay to about 0.3 seconds.

**Comment by thestinger** [comment]
@jhass: Changing `uint8_t buffer[BUFSIZ];` to `uint8_t buffer[256]` would no doubt make it even faster, but I'm going to have to find a good balance between performance and responsiveness. Sending the output over a network is somewhat of a niche: the timeout still needs to work (i.e. not loop forever) but I don't want to sacrifice too much throughput to make it responsive.

**Comment by jhass** [comment]
Sure, as said I totally could live even with the extra 1.3 seconds for my usecase.

**Comment by thestinger** [comment]
BTW, this is basically caused by a POSIX design flaw. Ideally, I could just do non-blocking output with `stdout` and `stderr` and there would be no issue here at all. It would only write when the pipe to ssh was ready to receive more input immediately. Sadly, you can't really use `O_NONBLOCK` on `stdout` and `stderr` because POSIX decided to associate with the instance of the open file rather than the file descriptors or the system calls so it can break other processes sharing the open file instance if they don't expect it.

There might be a nice hack to work around this... but nothing perfect.

**Comment by thestinger** [comment]
(it would still need an arbitrary iteration limit to deal with regular files, but the case where `stdout` is a pipe case would never block)

**Comment by thestinger** [comment]
Another way to handle this properly would be to use a thread for each standard stream with non-blocking pipes (or `eventfd`, to avoid copying) used to communicate with each one.

**Comment by jhass** [comment]
Thanks for the quick fix!

**Comment by jhass** [comment]
I didn't try to reproduce this in a local minimal setup yet, but maybe you can answer this on a quick glance, could it be that the issue is still there for standard error?
```c
#include <stdio.h>
int main(void) {
  while (1) fprintf(stderr, "a");
}
```

**Comment by thestinger** [comment]
It should work the same way for both.
