### ISSUE TITLE
SIGCHLD not delivered after fork.

### ISSUE THREAD

**Issue by technorama** [thestinger/playpen#52]
A process should receive SIGCHLD after forking.  This doesn't appear to happen when running in playpen.

Here's a test case that should print "received_signal" on stderr.
https://gist.github.com/technorama/da75d27b6310935ba44e

**Comment by thestinger** [comment]
Does this happen without learning mode enabled too?

**Comment by jhass** [comment]
Yes.

**Comment by thestinger** [comment]
Interesting. I thought this would just be a problem in 0d7727046ec63b2d6963fb07899f63845fbbfecd incorrectly but that's not it.

**Comment by thestinger** [comment]
Ah, I might just need to reset the signal mask for the child...
