### ISSUE TITLE
Mono's C# shell can only quit while learning mode is on, but when the created syscalls file is used with learning mode off, it can't

### ISSUE THREAD

**Issue by angelsl** [thestinger/playpen#55]
Mono's C# shell can quit while learning mode is on, but when the created syscalls file is used with learning mode off, it can't.

It's just strange.

This is the command line I'm using, with `-L` added for learning mode:

````
playpen sandbox --mount-proc --user=sandbox -S mono_syscalls --devices=/dev/urandom:r,/dev/null:w -- /usr/bin/mono -v /usr/lib/mono/4.5/csharp.exe
````

It happens on both the current Arch version and Git head.

**Comment by thestinger** [comment]
The learning mode doesn't currently trace anything other than the main thread, so it won't necessarily add everything that's required.

**Comment by thestinger** [comment]
See #53. That's probably the issue.

**Comment by angelsl** [comment]
Oh. Makes sense. Is there any way to determine what syscalls I need to enable?

**Comment by angelsl** [comment]
Yeah, `strace`. Sorry for wasting your time ><

**Comment by thestinger** [comment]
I'll get around to fixing this deficiency soon but I just haven't had time yet.

**Comment by angelsl** [comment]
Strange. Adding in all the syscalls reported by `strace` doesn't help.

**Comment by thestinger** [comment]
You need `strace -f` to trace more than the main thread.

**Comment by angelsl** [comment]
That did it. Thank you so much!

**Comment by thestinger** [comment]
@angelsl: BTW, tracing child processes is now implemented in master.
