### ISSUE TITLE
playpen: application terminated abnormally with signal 31 (Bad system call)

### ISSUE THREAD

**Issue by mtahmed** [thestinger/playpen#56]
The issue happens regardless of what I am trying to run. E.g `sudo playpen sandbox --timeout=100000 -- foo` or `sudo playpen sandbox -- ls` give the same error.

I am running this on archlinux. Are there perhaps some setup steps that I am missing?

**Comment by thestinger** [comment]
You need to have it learn a list of system calls. See this example: https://github.com/thestinger/playpen#example.

**Comment by thestinger** [comment]
You can just leave it in learning mode for a while to set something up rather than enforcing it. But it's intended that a system call whitelist will always be used in a real production deployment.

**Comment by mtahmed** [comment]
Ah I see - I was using the rust-playpen whitelist and that didn't seem to work. It works in learning mode.

**Comment by thestinger** [comment]
And then it will append the system calls that are required so the enforcing mode should start working.

**Comment by thestinger** [comment]
Should just start without a pre-populated whitelist though, especially since it has fine-grained learning with parameter filters for stuff like ioctl now.
