### ISSUE TITLE
Prevent fork bombs

### ISSUE THREAD

**Issue by mtahmed** [thestinger/playpen#57]
Running

`sandbox --tasks-max=1 --syscalls-file=whitelist --timeout=5 --memory-limit=64 --learn -- ruby -e 'loop { fork }`

kills the application:

`playpen: application terminated abnormally with signal 9 (Killed)`

But the fork bomb still goes through and keeps forking until the machine crashes. Am I missing something? Is whitelist the way to prevent this?

**Comment by jhass** [comment]
`-T 512` should help.

**Comment by thestinger** [comment]
The memory limit and task limit both work fine here. If the resource limits aren't working, then something is wrong with control groups on your system.

**Comment by thestinger** [comment]
It's worth noting that the ability to limit the number of tasks is very new. The memory limit prevents a fork bomb though, and the CPU shares are provided to the group as a whole so it shouldn't get an unfair amount of resources. Perhaps you're on a distribution disabling the memory control group functionality by default (Debian-based?).

**Comment by mtahmed** [comment]
The cgroups mounted on my system are pasted below. The cpuacct cgroup isn't mounted. Could that be the issue?

```
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/bfqio type cgroup (rw,nosuid,nodev,noexec,relatime,bfqio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
```

**Comment by thestinger** [comment]
Also, if the main process dies then the whole group of processes should die with it due to the process namespace. Can you try with a vanilla kernel?

**Comment by thestinger** [comment]
It does make sense that a DoS could happen if the memory limit is too high and there's no support for the new pids control group but... the main process is dying for you so all of the processes should be dying with it because PID1 in the process namespace acts as init.

**Comment by thestinger** [comment]
And if the cpu,cpuacct control group was mounted, it wouldn't be grabbing a ridiculous amount of CPU shares.

**Comment by mtahmed** [comment]
I was using the `linux-cf` kernel which was causing the problems. Using a vanilla kernel fixed the problem. It also mounted the _missing_ cgroups:

```
tmpfs on /sys/fs/cgroup type tmpfs (rw,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,clone_children)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgmfs on /run/cgmanager/fs type tmpfs (rw,relatime,size=100k,mode=755)
```

**Comment by thestinger** [comment]
The lack of the CPU control group might have just resulted in the machine being hopelessly overloaded. It's strange that the process control group wasn't resulting in everything being torn down quickly when the main process died though.

**Comment by thestinger** [comment]
Anyway, soon the pids control group will be available (systemd already supports it, and Playpen uses it via that API) so the tasks limit will actually be enforced, and this won't only be enforced indirectly via the memory control group with the CPU control group mitigating the damage.
