### ISSUE TITLE
A decent tutorial?

### ISSUE THREAD

**Issue by emotionally-exhausted** [thestinger/playpen#66]
At the risk of sounding stupid, how do I use this? I'm running Arch linux build 231, updated regularly, and have satisfied the dependencies. Thinking I would have need for more than one instance I created a directory named "sandbox" in my home directory, and inside that another directory named "h265" after the video codec I'll be using.

Following the example I entered "pacstrap -cd h265" in terminal (open in sandbox, of course) and received a notice that pacstrap was not installed.

I'm obviously in over my head here. Can anyone direct me to a comprehensive tutorial? I'm sure you're probably too busy to hold my hand on this.

**Comment by dkasak** [comment]
@emotionally-exhausted FWIW, `pacstrap` is supplied by the `extra/arch-install-scripts` package so you should install that.
